//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsBackend.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternativeMeasure
    {
        public int ID { get; set; }
        public Nullable<int> MeasureID { get; set; }
        public Nullable<float> Multiplier { get; set; }
        public string Name { get; set; }
    
        public virtual MeasureUnit MeasureUnit { get; set; }
    }
}
