//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsBackend.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.Recepient_Ingredient = new HashSet<Recepient_Ingredient>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Сalories { get; set; }
        public int Fats { get; set; }
        public int Сarbohydrates { get; set; }
        public int Proteins { get; set; }
        public int MeasureID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepient_Ingredient> Recepient_Ingredient { get; set; }
        public virtual MeasureUnit MeasureUnit { get; set; }
    }
}
