//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsBackend.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dscorers_victorEntities : DbContext
    {
        public dscorers_victorEntities()
            : base("name=dscorers_victorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Recepient_Ingredient> Recepient_Ingredient { get; set; }
        public virtual DbSet<AlternativeMeasure> AlternativeMeasures { get; set; }
        public virtual DbSet<MeasureUnit> MeasureUnits { get; set; }
    }
}
